# PersistentVolumeClaim for MinIO data

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc
  namespace: minio
  labels:
    app.kubernetes.io/name:      minio
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "ceph-rbd-sc"
