# Secret for MinIO

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
  labels:
    app.kubernetes.io/name:      minio
    app.kubernetes.io/component: secret
type: Opaque
data:
  MINIO_ROOT_USER:     bWluaW9hZG1pbg==
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==
